create table if not exists public.telemetry_messages (
  id bigint generated by default as identity primary key,
  topic text not null,
  received_at timestamptz not null default now(),
  raw text not null,
  value jsonb not null
);

create index if not exists telemetry_messages_topic_received_at_idx
  on public.telemetry_messages (topic, received_at desc);

alter table public.telemetry_messages enable row level security;

revoke all on table public.telemetry_messages from anon, authenticated;
revoke all on sequence public.telemetry_messages_id_seq from anon, authenticated;
